INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent)
VALUES
    ('GOODY_MILITARY_GRANT_HEAVY_CAVALRY', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
    ('GOODY_MILITARY_GRANT_LIGHT_CAVALRY', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1),
    ('GOODY_MILITARY_GRANT_SIEGE', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1);

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES
    ('GOODY_MILITARY_GRANT_RECON', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, 'PLAYER_IS_AI'),
    ('GOODY_MILITARY_GRANT_RANGED', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, 'PLAYER_IS_AI'),
    ('GOODY_MILITARY_GRANT_ANTI_CAVALRY', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, 'PLAYER_IS_AI');

INSERT INTO ModifierArguments (ModifierId, Name, Type, Value)
VALUES
    ('GOODY_MILITARY_GRANT_RECON', 'UnitPromotionClassType', 'AGRTYPE_IDENTITY', 'PROMOTION_CLASS_RECON'),
    ('GOODY_MILITARY_GRANT_RANGED', 'UnitPromotionClassType', 'AGRTYPE_IDENTITY', 'PROMOTION_CLASS_RANGED'),
    ('GOODY_MILITARY_GRANT_ANTI_CAVALRY', 'UnitPromotionClassType', 'AGRTYPE_IDENTITY', 'PROMOTION_CLASS_ANTI_CAVALRY'),
    ('GOODY_MILITARY_GRANT_HEAVY_CAVALRY', 'UnitPromotionClassType', 'AGRTYPE_IDENTITY', 'PROMOTION_CLASS_HEAVY_CAVALRY'),
    ('GOODY_MILITARY_GRANT_LIGHT_CAVALRY', 'UnitPromotionClassType', 'AGRTYPE_IDENTITY', 'PROMOTION_CLASS_LIGHT_CAVALRY'),
    ('GOODY_MILITARY_GRANT_SIEGE', 'UnitPromotionClassType', 'AGRTYPE_IDENTITY', 'PROMOTION_CLASS_SIEGE');

INSERT INTO GoodyHutSubTypes (GoodyHut, SubTypeGoodyHut, Weight, ModifierId, MinOneCity, RequiresUnit, Description, Turn)
VALUES
    ('GOODYHUT_MILITARY', 'GOODYHUT_GRANT_RECON', 10, 'GOODY_MILITARY_GRANT_RECON', 1, 1, 'LOC_GOODY_NULL_DESCRIPTION', 2),
    ('GOODYHUT_MILITARY', 'GOODYHUT_GRANT_RANGED', 10, 'GOODY_MILITARY_GRANT_RANGED', 1, 1, 'LOC_GOODY_NULL_DESCRIPTION', 2),
    ('GOODYHUT_MILITARY', 'GOODYHUT_GRANT_ANTI_CAVALRY', 10, 'GOODY_MILITARY_GRANT_ANTI_CAVALRY', 1, 1, 'LOC_GOODY_NULL_DESCRIPTION', 2),
    ('GOODYHUT_MILITARY', 'GOODYHUT_GRANT_HEAVY_CAVALRY', 35, 'GOODY_MILITARY_GRANT_HEAVY_CAVALRY', 1, 1, 'LOC_GOODY_GRANT_HEAVY_CAVALRY_UNIT_DESCRIPTION', 2),
    ('GOODYHUT_MILITARY', 'GOODYHUT_GRANT_LIGHT_CAVALRY', 10, 'GOODY_MILITARY_GRANT_LIGHT_CAVALRY', 1, 1, 'LOC_GOODY_GRANT_LIGHT_CAVALRY_UNIT_DESCRIPTION', 2),
    ('GOODYHUT_MILITARY', 'GOODYHUT_GRANT_SIEGE', 25, 'GOODY_MILITARY_GRANT_SIEGE', 1, 1, 'LOC_GOODY_GRANT_SIEGE_UNIT_DESCRIPTION', 2);

INSERT INTO GoodyHutSubTypes (GoodyHut, SubTypeGoodyHut, Weight, ModifierId, MinOneCity, RequiresUnit, Turn)
VALUES
    ('GOODYHUT_CULTURE', 'GOODYHUT_TWO_CIVICS', 5, 'BOLSHOI_THEATRE_FREE_CIVICS', 1, 0, 0),
    ('GOODYHUT_SCIENCE', 'GOODYHUT_TWO_TECHS', 5, 'OXFORD_UNIVERSITY_FREE_TECHS', 1, 0, 0);

--INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent)
--VALUES
--    ('GOODY_CULTURE_GRANT_ONE_CIVIC', 'MODIFIER_PLAYER_GRANT_RANDOM_CIVIC', 1, 1);

UPDATE Units SET PrereqTech = NULL WHERE UnitType = 'UNIT_HORSEMAN';
UPDATE Units SET PrereqTech = NULL WHERE UnitType = 'UNIT_HEAVY_CHARIOT';
UPDATE Units SET PrereqTech = NULL WHERE UnitType = 'UNIT_CATAPULT';
UPDATE Units SET PrereqTech = NULL WHERE UnitType = 'UNIT_SPEARMAN';

INSERT INTO BarbarianTribeUnits (TribeType, UnitType, MinimumTurn, MaximumTurn, Weight)
VALUES
    ('BARBARIAN_TRIBE_LAND', 'UNIT_SETTLER', 0, 500, 10),
    ('BARBARIAN_TRIBE_LAND', 'UNIT_BUILDER', 0, 500, 10),
    ('BARBARIAN_TRIBE_LAND', 'UNIT_MEDIC', 0, 500, 10),
    ('BARBARIAN_TRIBE_LAND', 'UNIT_OBSERVATION_BALLOON', 0, 500, 10),
    ('BARBARIAN_TRIBE_HORSE', 'UNIT_SETTLER', 0, 500, 10),
    ('BARBARIAN_TRIBE_HORSE', 'UNIT_BUILDER', 0, 500, 10),
    ('BARBARIAN_TRIBE_HORSE', 'UNIT_MEDIC', 0, 500, 10),
    ('BARBARIAN_TRIBE_HORSE', 'UNIT_OBSERVATION_BALLOON', 0, 500, 10);


